version: '3'

services:

  streaming-consumer:
    image: codeworksio/nginx
    container_name: streaming-consumer
    volumes:
      - /home/centos/lightsail-streaming-server/www/:/var/www:ro
    ports:
      - "8080:8080"

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=${TZ}
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
    volumes:
      - /home/centos/duckdns/config:/config #optional
    restart: unless-stopped
